data_dir: /data/wufan/data/open_dataset_ocr_line/BAIDU
train_data:
  - /data/wufan/data/open_dataset_ocr_line/BAIDU/train.txt
test_data:
  - /data/wufan/data/open_dataset_ocr_line/BAIDU/val.txt

num_train_epochs: 10
eval_steps: 10000
save_steps: 10000
max_target_length: 25
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
checkpoint_path: /data1/wufan/ocr_experiments/rec/trocr-baidu
cust_data_init_weights_path: /data1/wufan/model/baidu-cust-data

